/**
 * Tailwind Styled Plugin Starter Template
 *
 * Copy folder ini dan rename sesuai nama plugin Anda.
 * Ganti semua TODO dengan implementasi Anda.
 *
 * Install ke project: tw plugin install <your-plugin-name>
 */
import type { TwPlugin } from "@tailwind-styled/plugin-api"

export interface MyPluginOptions {
  /**
   * TODO: Tambahkan option plugin Anda di sini
   */
  prefix?: string
  debug?: boolean
}

/**
 * TODO: Ganti nama dan deskripsi plugin
 */
const myPlugin = (options: MyPluginOptions = {}): TwPlugin => ({
  name: "my-tailwind-styled-plugin",

  setup(ctx) {
    const { prefix = "", debug = false } = options

    // ── 1. Register custom variants ─────────────────────────────────────────
    // ctx.addVariant("hocus", (selector) => `${selector}:hover, ${selector}:focus`)
    // ctx.addVariant("supports-grid", "@supports (display: grid)")

    // ── 2. Register design tokens ────────────────────────────────────────────
    // ctx.addToken("brand-blue", "#1d4ed8")
    // ctx.addToken("brand-red", "#dc2626")

    // ── 3. Register utility classes ──────────────────────────────────────────
    // ctx.addUtility("scrollbar-hide", {
    //   "-ms-overflow-style": "none",
    //   "scrollbar-width": "none",
    // })

    // ── 4. Transform component configs ───────────────────────────────────────
    // ctx.addTransform((config, meta) => {
    //   // Modify config before compilation
    //   return config
    // })

    // ── 5. Post-process generated CSS ────────────────────────────────────────
    // ctx.onGenerateCSS((css) => {
    //   return css + "\n/* Generated by my-plugin */"
    // })

    // ── 6. Run after build ───────────────────────────────────────────────────
    // ctx.onBuildEnd(async () => {
    //   if (debug) console.log("[my-plugin] Build complete")
    // })

    if (debug) {
      console.log(`[${myPlugin({}).name}] initialized with prefix: "${prefix}"`)
    }
  },
})

export default myPlugin
export { myPlugin }
