/**
 * tailwind-styled-v4 — Turbopack / Webpack Loader
 *
 * QA #7: Router-aware loader dengan:
 * - App Router vs Pages Router detection
 * - Directive preservation (use client / use server)
 * - Version-specific Next.js optimizations
 * - Source map passthrough
 * - Skip non-component files (node_modules, .d.ts, already transformed)
 */

import { type LoaderOutput, runLoaderTransform, registerFileClasses } from "@tailwind-styled/compiler/internal"
import fs from "node:fs"
import path from "node:path"

// ── Static CSS writer (identik dengan webpackLoader.ts) ─────────────────────
const _writtenRules = new Set<string>()

function appendStaticCssToFile(staticCss: string, safelistPath: string): void {
  if (!staticCss.trim() || !safelistPath) return
  const stateFilePath = path.join(path.dirname(safelistPath), "_tw-state-static.css")
  const newRules: string[] = []
  for (const chunk of staticCss.split(/(?<=\})\s*/)) {
    const rule = chunk.trim()
    if (rule && !_writtenRules.has(rule)) {
      _writtenRules.add(rule)
      newRules.push(rule)
    }
  }
  if (newRules.length === 0) return
  try {
    fs.mkdirSync(path.dirname(stateFilePath), { recursive: true })
    if (!fs.existsSync(stateFilePath)) {
      fs.writeFileSync(
        stateFilePath,
        `/* _tw-state-static.css — Auto-generated by tailwind-styled-v4. DO NOT EDIT.\n` +
        ` * Import di globals.css: @import "./_tw-state-static.css";\n` +
        ` * Berisi: state CSS (.tw-s-*[data-*="true"]) + container queries (@container .tw-cq-*).\n` +
        ` */\n\n`,
        "utf-8"
      )
    }
    fs.appendFileSync(stateFilePath, newRules.join("\n") + "\n", "utf-8")
  } catch { /* non-fatal */ }
}

export interface TurbopackContext {
  /** Absolute path ke file yang sedang di-transform */
  resourcePath: string
  /** Next.js version (jika di-inject oleh withTailwindStyled) */
  query?: Record<string, unknown>
}

export interface TurbopackLoaderOptions {
  addDataAttr?: boolean | string
  autoClientBoundary?: boolean | string
  hoist?: boolean | string
  preserveImports?: boolean | string
  /** Debug mode — log transform details */
  debug?: boolean | string
  /** Explicit Next.js major version */
  nextMajor?: number | string
  /** Path ke safelist CSS file — di-inject oleh withTailwindStyled (dev only) */
  safelistPath?: string
}

function parseBool(val: boolean | string | undefined, fallback = false): boolean {
  if (typeof val === "boolean") return val
  if (typeof val === "string") return val === "true" || val === "1"
  return fallback
}

function parseNum(val: number | string | undefined): number | undefined {
  if (typeof val === "number") return val
  if (typeof val === "string") return parseInt(val, 10) || undefined
  return undefined
}

function detectRouter(resourcePath: string): "app" | "pages" | "unknown" {
  const normalized = resourcePath.replace(/\\/g, "/")
  if (/\/app\//.test(normalized)) return "app"
  if (/\/pages\//.test(normalized)) return "pages"
  return "unknown"
}

/**
 * Next.js App Router entry-point files yang TIDAK boleh diproses loader ini.
 *
 * Turbopack tidak support `exclude` di rule level seperti webpack, sehingga
 * *.tsx glob akan match layout.tsx, page.tsx, dll. Guard ini memastikan loader
 * skip file-file tersebut secara eksplisit — identik dengan NEXT_RSC_ENTRIES
 * di withTailwindStyled.ts yang hanya efektif untuk webpack path.
 *
 * Tanpa guard ini: loader menyentuh layout.tsx → Next.js/React Compiler
 * kehilangan sinyal pure RSC → locale injection dari Accept-Language header
 * (Next.js 16+) tidak konsisten antara SSR pass dan hydration pass →
 * hydration mismatch `lang="id"` vs `lang="en"`.
 */
const NEXT_RSC_ENTRIES =
  /(?:^|[\\/])(?:layout|page|loading|error|not-found|template|default)\.[jt]sx?$/

function isSkippable(resourcePath: string): boolean {
  const normalized = resourcePath.replace(/\\/g, "/")
  return (
    normalized.includes("/node_modules/") ||
    normalized.endsWith(".d.ts") ||
    normalized.endsWith(".d.mts") ||
    normalized.endsWith(".d.cts") ||
    // Skip non-JS files that Turbopack may pass to the loader (no rule-level exclude)
    /\.(css|scss|sass|less|svg|png|jpg|jpeg|gif|webp|ico|woff|woff2|ttf|eot|md|mdx|txt|yaml|yml|json|tsbuildinfo)$/.test(normalized) ||
    // Skip Next.js RSC entry files — Turbopack tidak punya exclude di rule level,
    // jadi guard ini menggantikan NEXT_RSC_ENTRIES exclude yang ada di webpack path.
    NEXT_RSC_ENTRIES.test(normalized)
  )
}

/** Extract directive line dari source */
function extractDirective(source: string): { directive: string; stripped: string } {
  const match = source.match(/^(\s*["'](use client|use server)["']\s*;?\s*\n?)/)
  if (!match) return { directive: "", stripped: source }
  const directive = match[1].trim().replace(/['"]/g, '"') + "\n"
  const stripped = source.slice(match[0].length)
  return { directive, stripped }
}


// ─── Per-file safelist writer ─────────────────────────────────────────────────
// Turbopack tidak punya afterCompile hook dan bisa spawn multiple workers.
// Solusi: tiap file menulis file CSS-nya sendiri di .next/tw-classes/<slug>.css
// Tailwind scan seluruh direktori via @source ".next/tw-classes/**"
// Tidak ada race condition karena tiap file punya output path unik.
//
// Stale file handling:
// - Setiap dev server start, Next.js hapus .next/ → tw-classes/ otomatis hilang
// - Setiap compile cycle, TwSafelistDevPlugin (webpack) clear tw-classes/
// - Turbopack: pakai _cycle sentinel file — kalau cycle berubah, clear dulu

// ─── Cycle ID ─────────────────────────────────────────────────────────────────
// withTailwindStyled menulis _start.txt saat wrap() dipanggil (= saat next.config.ts
// di-load, yaitu sekali per dev server start). Setiap compile cycle Turbopack,
// loader baca _start.txt dan compare dengan _cycle.txt di tw-classes/:
//
//   _start.txt  = timestamp dev server start  (ditulis withTailwindStyled)
//   _cycle.txt  = timestamp cycle terakhir    (ditulis loader pertama di tiap cycle)
//
// Kalau _cycle.txt != _start.txt → compile cycle baru → clear tw-classes/ dulu.
// Ini solve masalah "file yang dihapus tetap ada di safelist" tanpa butuh hook.

const CYCLE_SENTINEL = "_cycle.txt"
const START_SENTINEL = "_start.txt"

// Cached per worker instance — hindari readFileSync berulang di file yang sama
const _workerCache = new Map<string, string>()

function getTwClassesDir(safelistPath: string): string {
  return path.join(path.dirname(safelistPath), "tw-classes")
}

function readSentinel(filePath: string): string {
  try { return fs.readFileSync(filePath, "utf-8").trim() } catch { return "" }
}

// Lock untuk serialisasi clearAndMarkCycle di dalam satu worker process.
// Turbopack bisa spawn multiple concurrent loader calls — tanpa lock,
// dua worker bisa clear tw-classes/ bersamaan → window dimana semua file
// hilang → Tailwind scan → CSS output kosong → FLICKER.
// Lock ini hanya efektif dalam satu Node.js process (per worker), tapi itu cukup
// karena Turbopack menggunakan single-threaded Node.js per worker.
let _clearLock = false

function clearAndMarkCycle(twClassesDir: string, startId: string): void {
  // Sudah ada clear yang sedang berjalan di worker ini — skip, biarkan yang pertama selesai.
  // Worker lain yang mungkin sudah clear duluan akan tulis _cycle.txt → kita akan
  // melihat cachedCycle === startId di iterasi berikutnya dan skip juga.
  if (_clearLock) return
  _clearLock = true
  try {
    if (fs.existsSync(twClassesDir)) {
      // Rename-then-recreate strategy: rename folder lama dulu, lalu buat folder baru kosong,
      // baru hapus folder lama. Ini memastikan tidak ada window dimana tw-classes/ tidak ada
      // atau kosong (yang akan bikin Tailwind re-scan dan generate CSS tanpa classes → flicker).
      const tempDir = `${twClassesDir}_clearing_${Date.now()}`
      try {
        fs.renameSync(twClassesDir, tempDir)
        fs.mkdirSync(twClassesDir, { recursive: true })
        // Copy _start.txt ke folder baru sebelum hapus folder lama
        const startFile = path.join(tempDir, START_SENTINEL)
        if (fs.existsSync(startFile)) {
          fs.copyFileSync(startFile, path.join(twClassesDir, START_SENTINEL))
        }
        // Copy _webpack-merged.css kalau ada
        const mergedFile = path.join(tempDir, "_webpack-merged.css")
        if (fs.existsSync(mergedFile)) {
          fs.copyFileSync(mergedFile, path.join(twClassesDir, "_webpack-merged.css"))
        }
        // Tulis _cycle.txt di folder baru SEBELUM hapus folder lama
        // Ini pastikan tw-classes/ selalu punya content valid
        fs.writeFileSync(path.join(twClassesDir, CYCLE_SENTINEL), startId, "utf-8")
        _workerCache.set(twClassesDir, startId)
        // Baru hapus folder lama secara async — tidak blokir compile
        fs.rmSync(tempDir, { recursive: true, force: true })
      } catch {
        // Fallback ke cara lama jika rename gagal (mis. cross-device)
        for (const file of fs.readdirSync(twClassesDir)) {
          if (file === START_SENTINEL || file === "_webpack-merged.css") continue
          try { fs.unlinkSync(path.join(twClassesDir, file)) } catch { /* non-fatal */ }
        }
        fs.writeFileSync(path.join(twClassesDir, CYCLE_SENTINEL), startId, "utf-8")
        _workerCache.set(twClassesDir, startId)
      }
    } else {
      fs.mkdirSync(twClassesDir, { recursive: true })
      fs.writeFileSync(path.join(twClassesDir, CYCLE_SENTINEL), startId, "utf-8")
      _workerCache.set(twClassesDir, startId)
    }
  } catch { /* non-fatal */ } finally {
    _clearLock = false
  }
}

function getPerFileSafelistPath(safelistDir: string, resourcePath: string): string {
  const normalized = resourcePath.replace(/\\/g, "/")
  const slug = normalized
    .replace(/^.*\/src\//, "")
    .replace(/\.[tj]sx?$/, "")
    .replace(/[^a-zA-Z0-9]/g, "_")
    .slice(0, 80)
  return path.join(safelistDir, `${slug}.css`)
}

function writePerFileSafelist(
  safelistPath: string | undefined,
  resourcePath: string,
  classes: string[]
): void {
  if (!safelistPath || classes.length === 0) return
  try {
    const twClassesDir = getTwClassesDir(safelistPath)

    // Baca start ID dari _start.txt (ditulis withTailwindStyled saat config load)
    const startId = readSentinel(path.join(twClassesDir, START_SENTINEL))

    // Compare dengan cycle ID terakhir — pakai in-memory cache dulu, fallback ke disk
    const cachedCycle = _workerCache.get(twClassesDir) ?? readSentinel(path.join(twClassesDir, CYCLE_SENTINEL))

    if (startId && cachedCycle !== startId) {
      // Compile cycle baru — clear tw-classes/ dan tulis _cycle.txt baru
      clearAndMarkCycle(twClassesDir, startId)
    } else if (!fs.existsSync(twClassesDir)) {
      fs.mkdirSync(twClassesDir, { recursive: true })
    }

    const outPath = getPerFileSafelistPath(twClassesDir, resourcePath)
    const sorted = [...new Set(classes)].sort()
    const css = [
      `/* tw-safelist: ${path.basename(resourcePath)} — auto-generated */`,
      "@layer utilities {",
      sorted.map((cls) => `.${cls.replace(/([^a-zA-Z0-9_-])/g, "\\$1")} {}`).join("\n"),
      "}",
    ].join("\n")

    // Skip write jika isi sama — avoid Tailwind re-scan yang tidak perlu
    try {
      if (fs.readFileSync(outPath, "utf-8") === css) return
    } catch { /* file belum ada, lanjut write */ }

    // Atomic write: tulis ke temp file dulu, lalu rename ke path final.
    // Ini mencegah Tailwind scanner membaca file yang sedang ditulis (partial read)
    // yang akan menghasilkan CSS incomplete → FLICKER.
    // rename() dijamin atomic di semua OS modern (POSIX dan Windows NTFS).
    const tmpPath = `${outPath}.tmp`
    try {
      fs.writeFileSync(tmpPath, css, "utf-8")
      fs.renameSync(tmpPath, outPath)
    } catch {
      // Fallback kalau rename gagal (mis. cross-device, Windows lock)
      try { fs.unlinkSync(tmpPath) } catch { /* ignore */ }
      fs.writeFileSync(outPath, css, "utf-8")
    }
  } catch {
    // Non-fatal
  }
}

/**
 * Main loader function — compatible dengan Turbopack, Webpack 5, rspack.
 */
export default function turbopackLoader(
  this: TurbopackContext,
  source: string,
  options: TurbopackLoaderOptions = {}
): string {
  // Skip files yang tidak perlu di-transform.
  // Exception: RSC entry files (page.tsx, layout.tsx, etc.) that have "use client"
  // are client components — they still need tw template literal transformation.
  if (isSkippable(this.resourcePath)) {
    const isRscEntry = NEXT_RSC_ENTRIES.test(this.resourcePath.replace(/\\/g, "/"))
    const hasUseClient = /^\s*["'](use client)["']/.test(source)
    if (!isRscEntry || !hasUseClient) return source
  }

  // Detect router context
  const router = detectRouter(this.resourcePath)
  const nextMajor = parseNum(options.nextMajor)
  const debug = parseBool(options.debug)
  const filename = path.basename(this.resourcePath)

  // Build effective options berdasarkan router context
  const effective = {
    addDataAttr: parseBool(options.addDataAttr),
    // App Router: selalu auto-detect client boundary
    // Pages Router: opt-in via option
    autoClientBoundary: router === "app" ? true : parseBool(options.autoClientBoundary),
    // Hoist by default untuk semua contexts
    hoist: parseBool(options.hoist, true),
    // Pages Router: preserve imports (RSC tidak berlaku)
    preserveImports: router === "pages" ? true : parseBool(options.preserveImports, false),
  }

  if (debug) {
    console.debug(`[tw-loader] ${filename}: router=${router} nextMajor=${nextMajor ?? "unknown"}`)
  }

  // Preserve directive (use client / use server)
  const { directive, stripped } = extractDirective(source)

  // ── Hash pre-embedding (build-time optimization) ────────────────────────
  // Inject `__hash: "abc123"` ke semua tw() calls yang punya states config.
  // stateEngine.ts akan pakai __hash langsung — skip runtime hashState() computation.
  // Zero dependency baru: pakai Rust NAPI yang sama dengan compiler.
  let processedSource = stripped
  try {
    const compilerMod = require("@tailwind-styled/compiler/internal") as {
      injectStateHash?: (source: string, filename: string) => { code: string; changed: boolean; injectedCount: number }
    }
    if (typeof compilerMod?.injectStateHash === "function" && stripped.includes("states:")) {
      const hashResult = compilerMod.injectStateHash(stripped, this.resourcePath)
      if (hashResult.changed) {
        processedSource = hashResult.code
        if (debug) {
          console.debug(`[tw-loader] ${filename}: injected __hash for ${hashResult.injectedCount} component(s)`)
        }
      }
    }
  } catch {
    // injectStateHash tidak tersedia (binary belum di-rebuild) — skip, tidak fatal
  }

  try {
    const output: LoaderOutput = runLoaderTransform({
      filepath: this.resourcePath,
      source: processedSource,
      options: effective,
    })

    // Tidak ada perubahan — Rust kembalikan source asli (bukan string kosong).
    // Guard lama `!output.code.length` selalu false karena code = original source.
    // Fix: cukup cek changed flag saja; return source asli agar Next.js RSC boundary
    // tetap intact dan tidak ada interaksi dengan React Compiler locale detection.
    if (!output.changed) {
      // Meski tidak ada transform, tetap tulis safelist kalau ada classes yang ditemukan.
      // Object config style (tw.div({...})) tidak butuh transform tapi tetap punya classes.
      if (output.classes.length > 0) {
        writePerFileSafelist(options.safelistPath, this.resourcePath, output.classes)
      }
      // Tetap collect static CSS meski file tidak di-transform
      if (output.staticCss && options.safelistPath) {
        appendStaticCssToFile(output.staticCss, options.safelistPath)
      }
      return source
    }

    // Register classes untuk route map (dipakai webpack dev plugin & build manifest)
    if (output.classes.length > 0) {
      registerFileClasses(this.resourcePath, output.classes)
      // Turbopack: tulis per-file safelist langsung dari loader.
      // Race-condition-safe karena tiap file punya output path unik.
      writePerFileSafelist(options.safelistPath, this.resourcePath, output.classes)
    }

    // ── Append static CSS (state + container) ──────────────────────────────
    if (output.staticCss && options.safelistPath) {
      appendStaticCssToFile(output.staticCss, options.safelistPath)
    }

    // Re-attach directive di depan
    if (!directive) return output.code

    // Strip any duplicate directives yang mungkin diinject oleh compiler
    const clean = output.code.replace(/^\s*["'](use client|use server)["']\s*;?\s*\n?/, "")
    return directive + clean
  } catch (err) {
    // Loader harus tidak pernah throw — return source asli dengan warning
    const msg = err instanceof Error ? err.message : String(err)
    if (debug) {
      console.warn(`[tw-loader] transform failed for ${filename}: ${msg}`)
    }
    return source
  }
}