#!/bin/bash

echo "=== Trace: Button ==="
echo "✓ defined in: src/components/Button.tsx:3"
echo "✓ variants: hover, focus, disabled"
echo "✓ sub-components:"
echo "   - icon → inline-block w-5 h-5"
echo "   - text → inline-block"
echo "   - badge → absolute -top-2 -right-2"
echo "✓ final style:"
echo "   position: relative"
echo "   display: inline-flex"
echo "   padding: 0.5rem 1rem"
echo "   background: #3b82f6 (blue-500)"
echo "   color: white"
echo "   border-radius: 0.5rem"
echo "✓ conflicts: none"
echo ""

echo "=== Trace: Button.icon ==="
echo "✓ inherited from: Button"
echo "✓ defined in: src/components/Button.tsx:10"
echo "✓ final style:"
echo "   display: inline-block"
echo "   width: 1.25rem"
echo "   height: 1.25rem"
echo "   transition-property: transform"
echo ""

echo "=== Doctor Diagnostics ==="
echo "✓ Scanned 12 components"
echo "✓ Found 3 issues:"
echo ""
echo "[Warning] Unused sub-component: Button.text"
echo "   Location: src/components/Button.tsx:16"
echo "   Suggestion: Remove or use in JSX"
echo ""
echo "[Info] Variant explosion detected: Button"
echo "   Location: src/components/Button.tsx"
echo "   Suggestion: Consider using cv() for complex variants"
echo ""
echo "[Warning] Duplicate styles: Card.body"
echo "   Location: src/components/Card.tsx:22"
echo "   Suggestion: Extract to shared utility"
echo ""

echo "=== Why: bg-red-500 ==="
echo "✓ Bundle contribution: 2.1 KB"
echo "✓ Used in: 3 components"
echo "   - src/components/Button.tsx:35"
echo "   - src/components/Alert.tsx:45"
echo "   - src/components/DangerButton.tsx:12"
echo "✓ Variant chain: hover:bg-red-600, focus:ring-red-400"
echo "✓ Impact: Medium risk (3 components)"
echo "✓ Potential savings: 0.5 KB"
echo "✓ Suggestion: Consider using semantic color tokens"