name: Feature request
description: Usulan fitur baru
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      placeholder: Problem apa yang ingin diselesaikan?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Solusi yang diusulkan
    validations:
      required: true
