/**
 * tailwind-styled-v4 - Rspack Loader v5
 *
 * v5 Changes:
 * - Mode always zero-runtime (no more runtime mode)
 * - Uses native binding from compiler
 * - Collects static state + container CSS per-file → _tw-state-static.css
 */

import { runLoaderTransform, shouldSkipFile } from "@tailwind-styled/compiler/internal"
import fs from "node:fs"
import path from "node:path"

interface RspackLoaderOptions {
  addDataAttr?: boolean
  preserveImports?: boolean
  /** Path ke safelist CSS file — untuk menulis _tw-state-static.css di sebelahnya */
  safelistPath?: string
}

interface RspackLoaderContext {
  resourcePath: string
  getOptions(): RspackLoaderOptions
  async(): (err: Error | null, result?: string) => void
}

// ── Static CSS writer (identik dengan webpackLoader.ts) ─────────────────────
const _writtenRules = new Set<string>()

function appendStaticCssToFile(staticCss: string, safelistPath: string): void {
  if (!staticCss.trim() || !safelistPath) return
  const stateFilePath = path.join(path.dirname(safelistPath), "_tw-state-static.css")
  const newRules: string[] = []
  for (const chunk of staticCss.split(/(?<=\})\s*/)) {
    const rule = chunk.trim()
    if (rule && !_writtenRules.has(rule)) {
      _writtenRules.add(rule)
      newRules.push(rule)
    }
  }
  if (newRules.length === 0) return
  try {
    fs.mkdirSync(path.dirname(stateFilePath), { recursive: true })
    if (!fs.existsSync(stateFilePath)) {
      fs.writeFileSync(
        stateFilePath,
        `/* _tw-state-static.css — Auto-generated by tailwind-styled-v4. DO NOT EDIT.\n` +
        ` * Import di CSS entry: @import "./_tw-state-static.css";\n` +
        ` * Berisi: state CSS (.tw-s-*[data-*="true"]) + container queries (@container .tw-cq-*).\n` +
        ` */\n\n`,
        "utf-8"
      )
    }
    fs.appendFileSync(stateFilePath, newRules.join("\n") + "\n", "utf-8")
  } catch { /* non-fatal */ }
}

export default function rspackLoader(this: RspackLoaderContext, source: string): void {
  const callback = this.async()
  const filepath = this.resourcePath

  if (shouldSkipFile(filepath) || filepath.includes(".rspack-dist")) {
    callback(null, source)
    return
  }

  try {
    const options = this.getOptions()

    const output = runLoaderTransform({
      filepath,
      source,
      options: {
        mode: "zero-runtime",
        addDataAttr: options.addDataAttr ?? true,
        hoist: true,
        filename: filepath,
        preserveImports: true,
      },
    })

    // ── Append static CSS (state + container) ──────────────────────────────
    if (output.staticCss && options.safelistPath) {
      appendStaticCssToFile(output.staticCss, options.safelistPath)
    }

    callback(null, output.changed ? output.code : source)
  } catch (err) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(`[tailwind-styled/rspack] Transform failed for ${filepath}:`, err)
    }
    callback(null, source)
  }
}