// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./tailwind-styled-native.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-android-arm64')
        const bindingPackageVersion = require('@tailwind-styled/native-android-arm64/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./tailwind-styled-native.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-android-arm-eabi')
        const bindingPackageVersion = require('@tailwind-styled/native-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./tailwind-styled-native.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-win32-x64-gnu')
        const bindingPackageVersion = require('@tailwind-styled/native-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./tailwind-styled-native.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-win32-x64-msvc')
        const bindingPackageVersion = require('@tailwind-styled/native-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./tailwind-styled-native.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-win32-ia32-msvc')
        const bindingPackageVersion = require('@tailwind-styled/native-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./tailwind-styled-native.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-win32-arm64-msvc')
        const bindingPackageVersion = require('@tailwind-styled/native-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./tailwind-styled-native.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@tailwind-styled/native-darwin-universal')
      const bindingPackageVersion = require('@tailwind-styled/native-darwin-universal/package.json').version
      if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./tailwind-styled-native.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-darwin-x64')
        const bindingPackageVersion = require('@tailwind-styled/native-darwin-x64/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./tailwind-styled-native.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-darwin-arm64')
        const bindingPackageVersion = require('@tailwind-styled/native-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./tailwind-styled-native.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-freebsd-x64')
        const bindingPackageVersion = require('@tailwind-styled/native-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./tailwind-styled-native.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-freebsd-arm64')
        const bindingPackageVersion = require('@tailwind-styled/native-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./tailwind-styled-native.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@tailwind-styled/native-linux-x64-musl')
          const bindingPackageVersion = require('@tailwind-styled/native-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./tailwind-styled-native.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@tailwind-styled/native-linux-x64-gnu')
          const bindingPackageVersion = require('@tailwind-styled/native-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./tailwind-styled-native.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@tailwind-styled/native-linux-arm64-musl')
          const bindingPackageVersion = require('@tailwind-styled/native-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./tailwind-styled-native.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@tailwind-styled/native-linux-arm64-gnu')
          const bindingPackageVersion = require('@tailwind-styled/native-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./tailwind-styled-native.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@tailwind-styled/native-linux-arm-musleabihf')
          const bindingPackageVersion = require('@tailwind-styled/native-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./tailwind-styled-native.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@tailwind-styled/native-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@tailwind-styled/native-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./tailwind-styled-native.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@tailwind-styled/native-linux-loong64-musl')
          const bindingPackageVersion = require('@tailwind-styled/native-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./tailwind-styled-native.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@tailwind-styled/native-linux-loong64-gnu')
          const bindingPackageVersion = require('@tailwind-styled/native-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./tailwind-styled-native.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@tailwind-styled/native-linux-riscv64-musl')
          const bindingPackageVersion = require('@tailwind-styled/native-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./tailwind-styled-native.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@tailwind-styled/native-linux-riscv64-gnu')
          const bindingPackageVersion = require('@tailwind-styled/native-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./tailwind-styled-native.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-linux-ppc64-gnu')
        const bindingPackageVersion = require('@tailwind-styled/native-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./tailwind-styled-native.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-linux-s390x-gnu')
        const bindingPackageVersion = require('@tailwind-styled/native-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./tailwind-styled-native.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-openharmony-arm64')
        const bindingPackageVersion = require('@tailwind-styled/native-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./tailwind-styled-native.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-openharmony-x64')
        const bindingPackageVersion = require('@tailwind-styled/native-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./tailwind-styled-native.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@tailwind-styled/native-openharmony-arm')
        const bindingPackageVersion = require('@tailwind-styled/native-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '5.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 5.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./tailwind-styled-native.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('@tailwind-styled/native-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.analyzeClasses = nativeBinding.analyzeClasses
module.exports.analyzeClassesWorkspace = nativeBinding.analyzeClassesWorkspace
module.exports.analyzeClassUsage = nativeBinding.analyzeClassUsage
module.exports.analyzeRouteClassDistribution = nativeBinding.analyzeRouteClassDistribution
module.exports.analyzeRsc = nativeBinding.analyzeRsc
module.exports.animationCacheKey = nativeBinding.animationCacheKey
module.exports.applyClassDiff = nativeBinding.applyClassDiff
module.exports.applyOpacity = nativeBinding.applyOpacity
module.exports.areClassSetsEqual = nativeBinding.areClassSetsEqual
module.exports.assembleCssIr = nativeBinding.assembleCssIr
module.exports.astExtractClasses = nativeBinding.astExtractClasses
module.exports.astExtractClasses = nativeBinding.astExtractClasses
module.exports.atomicRegistrySize = nativeBinding.atomicRegistrySize
module.exports.atomicRegistrySize = nativeBinding.atomicRegistrySize
module.exports.batchExtractClasses = nativeBinding.batchExtractClasses
module.exports.batchSplitClasses = nativeBinding.batchSplitClasses
module.exports.benchmarkStreamingVsBuffered = nativeBinding.benchmarkStreamingVsBuffered
module.exports.buildContainerRules = nativeBinding.buildContainerRules
module.exports.buildDependencyChain = nativeBinding.buildDependencyChain
module.exports.buildDistribution = nativeBinding.buildDistribution
module.exports.buildVariantLookupKey = nativeBinding.buildVariantLookupKey
module.exports.cachePriority = nativeBinding.cachePriority
module.exports.cachePriority = nativeBinding.cachePriority
module.exports.cacheRead = nativeBinding.cacheRead
module.exports.cacheRead = nativeBinding.cacheRead
module.exports.cacheWrite = nativeBinding.cacheWrite
module.exports.cacheWrite = nativeBinding.cacheWrite
module.exports.calculateBundleContributions = nativeBinding.calculateBundleContributions
module.exports.calculateImpact = nativeBinding.calculateImpact
module.exports.calculateImpactScores = nativeBinding.calculateImpactScores
module.exports.calculateRisk = nativeBinding.calculateRisk
module.exports.calculateRisk = nativeBinding.calculateRisk
module.exports.calculateSavings = nativeBinding.calculateSavings
module.exports.calculateSavings = nativeBinding.calculateSavings
module.exports.checkAgainstSafelist = nativeBinding.checkAgainstSafelist
module.exports.classifyAndSortClasses = nativeBinding.classifyAndSortClasses
module.exports.classifyKnownClasses = nativeBinding.classifyKnownClasses
module.exports.clearAllCachesNapi = nativeBinding.clearAllCachesNapi
module.exports.clearAtomicRegistry = nativeBinding.clearAtomicRegistry
module.exports.clearAtomicRegistry = nativeBinding.clearAtomicRegistry
module.exports.clearCompileCacheNapi = nativeBinding.clearCompileCacheNapi
module.exports.clearCssGenCacheNapi = nativeBinding.clearCssGenCacheNapi
module.exports.clearNameRegistries = nativeBinding.clearNameRegistries
module.exports.clearParseCacheNapi = nativeBinding.clearParseCacheNapi
module.exports.clearParseCacheNapiInner = nativeBinding.clearParseCacheNapiInner
module.exports.clearResolveCacheNapi = nativeBinding.clearResolveCacheNapi
module.exports.clearResolverPool = nativeBinding.clearResolverPool
module.exports.clearResolverPool = nativeBinding.clearResolverPool
module.exports.clearThemeCache = nativeBinding.clearThemeCache
module.exports.clearThemeCacheNapi = nativeBinding.clearThemeCacheNapi
module.exports.clearWatchStats = nativeBinding.clearWatchStats
module.exports.collectClassCounts = nativeBinding.collectClassCounts
module.exports.collectFiles = nativeBinding.collectFiles
module.exports.compileAnimation = nativeBinding.compileAnimation
module.exports.compileClassNapi = nativeBinding.compileClassNapi
module.exports.compileCss = nativeBinding.compileCss
module.exports.compileKeyframes = nativeBinding.compileKeyframes
module.exports.compileTheme = nativeBinding.compileTheme
module.exports.compileToCss = nativeBinding.compileToCss
module.exports.compileToCssBatch = nativeBinding.compileToCssBatch
module.exports.compileVariantTable = nativeBinding.compileVariantTable
module.exports.computeCacheStats = nativeBinding.computeCacheStats
module.exports.computeClassStats = nativeBinding.computeClassStats
module.exports.computeImpactMetadata = nativeBinding.computeImpactMetadata
module.exports.computeIncrementalDiff = nativeBinding.computeIncrementalDiff
module.exports.configureCacheBackend = nativeBinding.configureCacheBackend
module.exports.createFingerprint = nativeBinding.createFingerprint
module.exports.declarationMapToString = nativeBinding.declarationMapToString
module.exports.detectClassConflicts = nativeBinding.detectClassConflicts
module.exports.detectDeadCode = nativeBinding.detectDeadCode
module.exports.diffClassLists = nativeBinding.diffClassLists
module.exports.eliminateDeadCss = nativeBinding.eliminateDeadCss
module.exports.estimateOptimalBatchSize = nativeBinding.estimateOptimalBatchSize
module.exports.estimateOptimalCacheConfigNative = nativeBinding.estimateOptimalCacheConfigNative
module.exports.estimateStreamingBatchSize = nativeBinding.estimateStreamingBatchSize
module.exports.extractAllClasses = nativeBinding.extractAllClasses
module.exports.extractAndGenerateStateCss = nativeBinding.extractAndGenerateStateCss
module.exports.extractClassesFromSource = nativeBinding.extractClassesFromSource
module.exports.extractClassesFromSource = nativeBinding.extractClassesFromSource
module.exports.extractComponentUsage = nativeBinding.extractComponentUsage
module.exports.extractCssVars = nativeBinding.extractCssVars
module.exports.extractThemeFromCss = nativeBinding.extractThemeFromCss
module.exports.extractThemeFromCssClassified = nativeBinding.extractThemeFromCssClassified
module.exports.extractTwContainerConfigs = nativeBinding.extractTwContainerConfigs
module.exports.extractTwStateConfigs = nativeBinding.extractTwStateConfigs
module.exports.flattenAndResolve = nativeBinding.flattenAndResolve
module.exports.generateAtomicCss = nativeBinding.generateAtomicCss
module.exports.generateAtomicCss = nativeBinding.generateAtomicCss
module.exports.generateCss = nativeBinding.generateCss
module.exports.generateCssBatch = nativeBinding.generateCssBatch
module.exports.generateCssNative = nativeBinding.generateCssNative
module.exports.generateCssNative = nativeBinding.generateCssNative
module.exports.generateRuntimeStateCss = nativeBinding.generateRuntimeStateCss
module.exports.generateStaticStateCss = nativeBinding.generateStaticStateCss
module.exports.generateSubComponentTypes = nativeBinding.generateSubComponentTypes
module.exports.generateSuggestions = nativeBinding.generateSuggestions
module.exports.generateSystemTokenCss = nativeBinding.generateSystemTokenCss
module.exports.generateTypeDefinitions = nativeBinding.generateTypeDefinitions
module.exports.getActiveWatches = nativeBinding.getActiveWatches
module.exports.getCacheOptimizationHints = nativeBinding.getCacheOptimizationHints
module.exports.getCacheStats = nativeBinding.getCacheStats
module.exports.getCacheStats = nativeBinding.getCacheStats
module.exports.getMemoryRecommendationsNative = nativeBinding.getMemoryRecommendationsNative
module.exports.getMemoryStatsNative = nativeBinding.getMemoryStatsNative
module.exports.getOptimizationRecommendations = nativeBinding.getOptimizationRecommendations
module.exports.getParseStats = nativeBinding.getParseStats
module.exports.getRecommendedCacheConfig = nativeBinding.getRecommendedCacheConfig
module.exports.getResolverPoolStats = nativeBinding.getResolverPoolStats
module.exports.getResolverPoolStats = nativeBinding.getResolverPoolStats
module.exports.getThemeCacheStats = nativeBinding.getThemeCacheStats
module.exports.getWatchEvents = nativeBinding.getWatchEvents
module.exports.getWatchPerformance = nativeBinding.getWatchPerformance
module.exports.getWatchStats = nativeBinding.getWatchStats
module.exports.getWatchSystemStatus = nativeBinding.getWatchSystemStatus
module.exports.getWeek6FeaturesStatus = nativeBinding.getWeek6FeaturesStatus
module.exports.getWeek6OptimizationStatus = nativeBinding.getWeek6OptimizationStatus
module.exports.getWeek8OptimizationStatus = nativeBinding.getWeek8OptimizationStatus
module.exports.hashContent = nativeBinding.hashContent
module.exports.hashFile = nativeBinding.hashFile
module.exports.hashFileContent = nativeBinding.hashFileContent
module.exports.hasTwUsage = nativeBinding.hasTwUsage
module.exports.hasTwUsage = nativeBinding.hasTwUsage
module.exports.hoistComponents = nativeBinding.hoistComponents
module.exports.idRegistryActiveCount = nativeBinding.idRegistryActiveCount
module.exports.idRegistryCreate = nativeBinding.idRegistryCreate
module.exports.idRegistryDestroy = nativeBinding.idRegistryDestroy
module.exports.idRegistryGenerate = nativeBinding.idRegistryGenerate
module.exports.idRegistryLookup = nativeBinding.idRegistryLookup
module.exports.idRegistryNext = nativeBinding.idRegistryNext
module.exports.idRegistryReset = nativeBinding.idRegistryReset
module.exports.idRegistrySnapshot = nativeBinding.idRegistrySnapshot
module.exports.injectStateHash = nativeBinding.injectStateHash
module.exports.inspectCacheStats = nativeBinding.inspectCacheStats
module.exports.isAlreadyTransformed = nativeBinding.isAlreadyTransformed
module.exports.isAlreadyTransformed = nativeBinding.isAlreadyTransformed
module.exports.isCriticalClass = nativeBinding.isCriticalClass
module.exports.keyframesCacheKey = nativeBinding.keyframesCacheKey
module.exports.layoutClassesToCss = nativeBinding.layoutClassesToCss
module.exports.mergeCssDeclarations = nativeBinding.mergeCssDeclarations
module.exports.minifyCss = nativeBinding.minifyCss
module.exports.normalizeAndDedupClasses = nativeBinding.normalizeAndDedupClasses
module.exports.normalizeClassInput = nativeBinding.normalizeClassInput
module.exports.normalizeIterations = nativeBinding.normalizeIterations
module.exports.normalizeNumber = nativeBinding.normalizeNumber
module.exports.optimizeCss = nativeBinding.optimizeCss
module.exports.oxcExtractClasses = nativeBinding.oxcExtractClasses
module.exports.parseAtomicClass = nativeBinding.parseAtomicClass
module.exports.parseAtomicClass = nativeBinding.parseAtomicClass
module.exports.parseClass = nativeBinding.parseClass
module.exports.parseClasses = nativeBinding.parseClasses
module.exports.parseClasses = nativeBinding.parseClasses
module.exports.parseClassesFromString = nativeBinding.parseClassesFromString
module.exports.parseCssRules = nativeBinding.parseCssRules
module.exports.parseCssToRules = nativeBinding.parseCssToRules
module.exports.parseSubcomponentBlocksNapi = nativeBinding.parseSubcomponentBlocksNapi
module.exports.parseTemplate = nativeBinding.parseTemplate
module.exports.pluginCheckAllUpdates = nativeBinding.pluginCheckAllUpdates
module.exports.pluginSearch = nativeBinding.pluginSearch
module.exports.pluginSemverHasUpdate = nativeBinding.pluginSemverHasUpdate
module.exports.pluginValidateName = nativeBinding.pluginValidateName
module.exports.pluginVerifyIntegrity = nativeBinding.pluginVerifyIntegrity
module.exports.pollWatchEvents = nativeBinding.pollWatchEvents
module.exports.predictMemoryUsage = nativeBinding.predictMemoryUsage
module.exports.pregenerateStatesNapi = nativeBinding.pregenerateStatesNapi
module.exports.processFileChange = nativeBinding.processFileChange
module.exports.processTailwindCssLightning = nativeBinding.processTailwindCssLightning
module.exports.processTailwindCssWithTargets = nativeBinding.processTailwindCssWithTargets
module.exports.propertyIdToString = nativeBinding.propertyIdToString
module.exports.pruneStaleEntries = nativeBinding.pruneStaleEntries
module.exports.rebuildWorkspaceResult = nativeBinding.rebuildWorkspaceResult
module.exports.recommendCachingStrategy = nativeBinding.recommendCachingStrategy
module.exports.redisCacheClear = nativeBinding.redisCacheClear
module.exports.redisCacheHitRate = nativeBinding.redisCacheHitRate
module.exports.redisDelete = nativeBinding.redisDelete
module.exports.redisEnableCluster = nativeBinding.redisEnableCluster
module.exports.redisExists = nativeBinding.redisExists
module.exports.redisExpire = nativeBinding.redisExpire
module.exports.redisFlushDb = nativeBinding.redisFlushDb
module.exports.redisGet = nativeBinding.redisGet
module.exports.redisGetConfig = nativeBinding.redisGetConfig
module.exports.redisInfo = nativeBinding.redisInfo
module.exports.redisMget = nativeBinding.redisMget
module.exports.redisMonitor = nativeBinding.redisMonitor
module.exports.redisMset = nativeBinding.redisMset
module.exports.redisPing = nativeBinding.redisPing
module.exports.redisPoolConnect = nativeBinding.redisPoolConnect
module.exports.redisPoolStats = nativeBinding.redisPoolStats
module.exports.redisSet = nativeBinding.redisSet
module.exports.redisShutdown = nativeBinding.redisShutdown
module.exports.redisSyncNodes = nativeBinding.redisSyncNodes
module.exports.redisTtl = nativeBinding.redisTtl
module.exports.redisTypedStats = nativeBinding.redisTypedStats
module.exports.registerPropertyName = nativeBinding.registerPropertyName
module.exports.registerValueName = nativeBinding.registerValueName
module.exports.resetCacheStats = nativeBinding.resetCacheStats
module.exports.resetMemoryStats = nativeBinding.resetMemoryStats
module.exports.resetResolverPoolStats = nativeBinding.resetResolverPoolStats
module.exports.resolveBreakpoint = nativeBinding.resolveBreakpoint
module.exports.resolveCascade = nativeBinding.resolveCascade
module.exports.resolveClassNames = nativeBinding.resolveClassNames
module.exports.resolveColor = nativeBinding.resolveColor
module.exports.resolveColorCached = nativeBinding.resolveColorCached
module.exports.resolveConflictGroup = nativeBinding.resolveConflictGroup
module.exports.resolveFontSize = nativeBinding.resolveFontSize
module.exports.resolveFontSizeCached = nativeBinding.resolveFontSizeCached
module.exports.resolveSimpleVariants = nativeBinding.resolveSimpleVariants
module.exports.resolveSpacing = nativeBinding.resolveSpacing
module.exports.resolveSpacingCached = nativeBinding.resolveSpacingCached
module.exports.resolveThemeValue = nativeBinding.resolveThemeValue
module.exports.resolveVariants = nativeBinding.resolveVariants
module.exports.reverseLookupByProperty = nativeBinding.reverseLookupByProperty
module.exports.reverseLookupCacheSize = nativeBinding.reverseLookupCacheSize
module.exports.reverseLookupClearCache = nativeBinding.reverseLookupClearCache
module.exports.reverseLookupFindDependents = nativeBinding.reverseLookupFindDependents
module.exports.reverseLookupFromCss = nativeBinding.reverseLookupFromCss
module.exports.scanCacheGet = nativeBinding.scanCacheGet
module.exports.scanCacheInvalidate = nativeBinding.scanCacheInvalidate
module.exports.scanCachePut = nativeBinding.scanCachePut
module.exports.scanCacheStats = nativeBinding.scanCacheStats
module.exports.scanFile = nativeBinding.scanFile
module.exports.scanFileNative = nativeBinding.scanFileNative
module.exports.scanFilesBatch = nativeBinding.scanFilesBatch
module.exports.scanWorkspace = nativeBinding.scanWorkspace
module.exports.serializeCssRule = nativeBinding.serializeCssRule
module.exports.setWatchAggregation = nativeBinding.setWatchAggregation
module.exports.setWatchMetrics = nativeBinding.setWatchMetrics
module.exports.splitAnimateClasses = nativeBinding.splitAnimateClasses
module.exports.stableKeyframesEntries = nativeBinding.stableKeyframesEntries
module.exports.startWatch = nativeBinding.startWatch
module.exports.stopWatch = nativeBinding.stopWatch
module.exports.stopWatching = nativeBinding.stopWatching
module.exports.toAtomicClasses = nativeBinding.toAtomicClasses
module.exports.toAtomicClasses = nativeBinding.toAtomicClasses
module.exports.transformSource = nativeBinding.transformSource
module.exports.twClassesToCss = nativeBinding.twClassesToCss
module.exports.twMerge = nativeBinding.twMerge
module.exports.twMergeMany = nativeBinding.twMergeMany
module.exports.twMergeManyWithSeparator = nativeBinding.twMergeManyWithSeparator
module.exports.twMergeRaw = nativeBinding.twMergeRaw
module.exports.twMergeRawWithOptions = nativeBinding.twMergeRawWithOptions
module.exports.twMergeWithSeparator = nativeBinding.twMergeWithSeparator
module.exports.validateVariantConfig = nativeBinding.validateVariantConfig
module.exports.valueIdToString = nativeBinding.valueIdToString
module.exports.walkAndPrefilterSourceFiles = nativeBinding.walkAndPrefilterSourceFiles
module.exports.watchFiles = nativeBinding.watchFiles
