const scope = {
  include: ["src/**", "packages/**", "scripts/**", "examples/**", "test/**"],
  exclude: [
    "**/dist/**",
    "**/dist-electron/**",
    "**/.cache/**",
    "**/.next/**",
    "**/.turbo/**",
    "**/.tw-cache/**",
    "**/node_modules/**",
    "packages/_experiments/**",
    "**/*.d.ts",
    "**/*.d.cts",
    "**/*.d.mts",
    "native/**",
    "bindings/**",
    "**/*.node",
    "**/*.dll",
    "**/*.exe",
    "**/*.png",
    "**/*.jpg",
    "**/*.jpeg",
    "**/*.gif",
    "**/*.svg",
    "**/*.ico",
    "**/*.bmp",
    "**/*.webp",
    "**/*.avif",
    "**/*.woff",
    "**/*.woff2",
    "**/*.ttf",
    "**/*.eot",
    "**/*.mp4",
    "**/*.mp3",
    "**/*.wav",
    "**/*.pdf",
  ],
}

module.exports = {
  scope,
  forbidden: [],
  options: {
    baseDir: ".",
    cache: false,
    tsConfig: {
      fileName: "tsconfig.json",
    },
    enhancedResolveOptions: {
      exportsFields: ["exports"],
      conditionNames: ["import", "require", "default"],
    },
    doNotFollow: {
      path: "node_modules",
    },
    includeOnly: {
      path: ["^src(?:/|$)", "^packages(?:/|$)", "^scripts(?:/|$)", "^examples(?:/|$)", "^test(?:/|$)"],
    },
    exclude: {
      path: [
        "(?:^|/)dist(?:/|$)",
        "(?:^|/)dist-electron(?:/|$)",
        "(?:^|/)\\.cache(?:/|$)",
        "(?:^|/)\\.next(?:/|$)",
        "(?:^|/)\\.turbo(?:/|$)",
        "(?:^|/)\\.tw-cache(?:/|$)",
        "(?:^|/)node_modules(?:/|$)",
        "^packages/_experiments(?:/|$)",
        "^native(?:/|$)",
        "^bindings(?:/|$)",
        "\\.d\\.[cm]?tsx?$",
        "\\.(?:node|dll|exe|png|jpe?g|gif|svg|ico|bmp|webp|avif|woff2?|ttf|eot|mp4|mp3|wav|pdf)$",
      ],
    },
  },
}
